export const CLEAR_HISTORY = 'DATA/CLEAR_HISTORY'
export const ADD_HISTORY_ITEM = 'DATA/ADD_HISTORY_ITEM'
export const REMOVE_HISTORY_ITEM =
  'DATA/REMOVE_HISTORY_ITEM'
export const UPDATE_USER_INPUT = 'DATA/UPDATE_USER_INPUT'
export const SET_EXPRESSION = 'DATA/SET_EXPRESSION'
export const CLEAR_EXPRESSION = 'DATA/CLEAR_EXPRESSION'
export const CHANGE_COMPONENTS_TYPE =
  'SETTINGS/CHANGE_COMPONENTS_TYPE'
export const CHANGE_THEME = 'SETTINGS/CHANGE_THEME'
export const INITIALIZE_CHANGE_THEME =
  'SETTINGS/INITIALIZE_CHANGE_THEME'
export const CHANGE_EXPRESSION_TYPE =
  'SETTINGS/CHANGE_EXPRESSION_TYPE'
export const CHANGE_CALCULATOR_TYPE =
  'SETTINGS/CHANGE_CALCULATOR_TYPE'
