export const KEYS = [
  {
    id: '1',
    key: 'C',
    keyName: 'clear',
    type: 'clearAll',
    payload: '',
  },
  {
    id: '2',
    key: '7',
    keyName: 'seven',
    type: 'addDigit',
    payload: '7',
  },
  {
    id: '3',
    key: '8',
    keyName: 'eight',
    type: 'addDigit',
    payload: '8',
  },
  {
    id: '4',
    key: '9',
    keyName: 'nine',
    type: 'addDigit',
    payload: '9',
  },
  {
    id: '5',
    key: '*',
    keyName: 'multiply',
    type: 'addOperator',
    payload: 'multiply',
  },
  {
    id: '6',
    key: '-',
    keyName: 'subtract',
    type: 'addOperator',
    payload: 'subtract',
  },
  {
    id: '7',
    key: '4',
    keyName: 'four',
    type: 'addDigit',
    payload: '4',
  },
  {
    id: '8',
    key: '5',
    keyName: 'five',
    type: 'addDigit',
    payload: '5',
  },
  {
    id: '9',
    key: '6',
    keyName: 'six',
    type: 'addDigit',
    payload: '6',
  },
  {
    id: '10',
    key: '\\',
    keyName: 'divide',
    type: 'addOperator',
    payload: 'divide',
  },
  {
    id: '11',
    key: '+',
    keyName: 'add',
    type: 'addOperator',
    payload: 'add',
  },
  {
    id: '12',
    key: '1',
    keyName: 'one',
    type: 'addDigit',
    payload: '1',
  },
  {
    id: '13',
    key: '2',
    keyName: 'two',
    type: 'addDigit',
    payload: '2',
  },
  {
    id: '14',
    key: '3',
    keyName: 'three',
    type: 'addDigit',
    payload: '3',
  },
  {
    id: '15',
    key: '=',
    keyName: 'calculate',
    type: 'calculate',
    payload: '',
  },
  {
    id: '16',
    key: '.',
    keyName: 'dot',
    type: 'addDot',
    payload: '',
  },
  {
    id: '17',
    key: '(',
    keyName: 'open bracket',
    type: 'addBracket',
    payload: 'open',
  },
  {
    id: '18',
    key: '0',
    keyName: 'zero',
    type: 'addDigit',
    payload: '0',
  },
  {
    id: '19',
    key: ')',
    keyName: 'close bracket',
    type: 'addBracket',
    payload: 'close',
  },
  {
    id: '20',
    key: 'CE',
    keyName: 'clear entry',
    type: 'clearEntry',
    payload: '',
  },
]
