export const KEYS = [
  { id: '1', key: 'C', keyName: 'clear' },
  { id: '2', key: '7', keyName: 'seven' },
  { id: '3', key: '8', keyName: 'eight' },
  { id: '4', key: '9', keyName: 'nine' },
  { id: '5', key: '*', keyName: 'multiply' },
  { id: '6', key: '-', keyName: 'subtract' },
  { id: '7', key: '4', keyName: 'four' },
  { id: '8', key: '5', keyName: 'five' },
  { id: '9', key: '6', keyName: 'six' },
  { id: '10', key: '\\', keyName: 'divide' },
  { id: '11', key: '+', keyName: 'add' },
  { id: '12', key: '1', keyName: 'one' },
  { id: '13', key: '2', keyName: 'two' },
  { id: '14', key: '3', keyName: 'three' },
  { id: '15', key: '=', keyName: 'calculate' },
  { id: '16', key: '.', keyName: 'dot' },
  { id: '17', key: '(', keyName: 'open bracket' },
  { id: '18', key: '0', keyName: 'zero' },
  { id: '19', key: ')', keyName: 'close bracket' },
  { id: '20', key: 'CE', keyName: 'clear entry' },
]
